package traductormorse;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;

/**
 *
 * @author Heydi y sus cabras del monte
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        btnParar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textIntroducir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMorse = new javax.swing.JTextArea();
        btnTraducir = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        sliderVelocidad = new javax.swing.JSlider();
        labelTraducir = new javax.swing.JLabel();
        labelVelocidad = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traductor Morse");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(506, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        textIntroducir.setForeground(new java.awt.Color(102, 102, 102));
        textIntroducir.setText("¡Hola Mundo!");
        textIntroducir.setToolTipText("Ingresa una lìnea de texto a convertir");
        textIntroducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textIntroducirMouseClicked(evt);
            }
        });
        getContentPane().add(textIntroducir);
        textIntroducir.setBounds(20, 50, 460, 30);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textMorse.setEditable(false);
        textMorse.setColumns(20);
        textMorse.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        textMorse.setRows(5);
        textMorse.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(textMorse);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 460, 50);

        btnTraducir.setBackground(new java.awt.Color(0, 120, 215));
        btnTraducir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnTraducir.setForeground(new java.awt.Color(153, 204, 255));
        btnTraducir.setText("Traducir");
        btnTraducir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraducirActionPerformed(evt);
            }
        });
        getContentPane().add(btnTraducir);
        btnTraducir.setBounds(230, 100, 150, 60);

        btnParar.setBackground(new java.awt.Color(255, 0, 51));
        btnParar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnParar.setForeground(new java.awt.Color(255, 153, 153));
        btnParar.setText("Parar");
        btnParar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });
        getContentPane().add(btnParar);
        btnParar.setBounds(390, 100, 90, 60);

        sliderVelocidad.setBackground(java.awt.Color.white);
        sliderVelocidad.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sliderVelocidad.setForeground(new java.awt.Color(0, 120, 215));
        sliderVelocidad.setMajorTickSpacing(10);
        sliderVelocidad.setMaximum(50);
        sliderVelocidad.setMinimum(10);
        sliderVelocidad.setMinorTickSpacing(10);
        sliderVelocidad.setPaintLabels(true);
        sliderVelocidad.setToolTipText("Palabras por minuto");
        sliderVelocidad.setValue(30);
        sliderVelocidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sliderVelocidad.setOpaque(false);
        getContentPane().add(sliderVelocidad);
        sliderVelocidad.setBounds(20, 120, 200, 42);
        sliderVelocidad.getAccessibleContext().setAccessibleName("");

        labelTraducir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTraducir.setForeground(new java.awt.Color(160, 160, 160));
        labelTraducir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTraducir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelTraducir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Introducir Texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 120, 215))); // NOI18N
        getContentPane().add(labelTraducir);
        labelTraducir.setBounds(10, 20, 480, 70);

        labelVelocidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelVelocidad.setForeground(new java.awt.Color(0, 120, 215));
        labelVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVelocidad.setText("Velocidad (ppm)");
        labelVelocidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelVelocidad);
        labelVelocidad.setBounds(60, 100, 120, 17);
        getContentPane().add(separator);
        separator.setBounds(20, 170, 460, 2);

        progressBar.setBackground(new java.awt.Color(102, 102, 102));
        progressBar.setToolTipText("");
        progressBar.setStringPainted(true);
        getContentPane().add(progressBar);
        progressBar.setBounds(0, 249, 500, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraducirActionPerformed
        try {
            btnParar.setEnabled(true);
            Morse datos = new Morse();
            Beep beep = new Beep();
            datos.codigo();
            int ppm = sliderVelocidad.getValue();
            String texto = datos.convertir(textIntroducir.getText());
            textMorse.setText(texto);
            int tiempo = 1200 / ppm;
            int dit = tiempo;
            int dah = tiempo * 3;
            int espacio = tiempo * 5;
            Beep.tono(dit); //prueba de sonido
            Beep.tono(dit);
            Beep.tono(dit);
            Beep.tono(dit);
            btnParar.setEnabled(false);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTraducirActionPerformed

    private void textIntroducirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIntroducirMouseClicked
        textIntroducir.setText(null);
        textIntroducir.setForeground(Color.BLACK);
    }//GEN-LAST:event_textIntroducirMouseClicked

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        
        btnParar.setEnabled(false);
    }//GEN-LAST:event_btnPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnTraducir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTraducir;
    private javax.swing.JLabel labelVelocidad;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JSeparator separator;
    private javax.swing.JSlider sliderVelocidad;
    private javax.swing.JTextField textIntroducir;
    private javax.swing.JTextArea textMorse;
    // End of variables declaration//GEN-END:variables
}
